telemetry-before: {"at": "2026-10-04T06:39:31.348381+00:00", "pageSize": 16384, "pages": {"Pages free": 14505, "Pages inactive": 300636, "Pages speculative": 667}, "availableBytes": 5174198272, "availableGiB": 4.819, "pressure": 1, "cpuIdlePercent": 81.37, "cpu": "7.24% user, 11.37% sys, 81.37% idle", "diskFreeBytes": 804536999936, "diskFreeGiB": 749.283, "heavyEligible": true}
container=crew-v2-test-0dc557cb-db54-42b2-ae3b-1e1ffacbcaee id=d3fb23cfe1e300c4003ec00503c900f25aba0472a9f3aebecfb3169bc0e96ce4 port=22386
telemetry-node: {"at": "2026-10-04T06:39:33.099746+00:00", "pageSize": 16384, "pages": {"Pages free": 4082, "Pages inactive": 301071, "Pages speculative": 4381}, "availableBytes": 5071405056, "availableGiB": 4.723, "pressure": 1, "cpuIdlePercent": 79.38, "cpu": "8.93% user, 11.68% sys, 79.38% idle", "diskFreeBytes": 804488421376, "diskFreeGiB": 749.238, "heavyEligible": true}
exit=1
leftover_dbs=0
after-stop: 0 containers; node: 0
telemetry-after: {"at": "2026-10-04T06:39:45.455493+00:00", "pageSize": 16384, "pages": {"Pages free": 8878, "Pages inactive": 292579, "Pages speculative": 2395}, "availableBytes": 4978311168, "availableGiB": 4.636, "pressure": 1, "cpuIdlePercent": 79.73, "cpu": "6.86% user, 13.39% sys, 79.73% idle", "diskFreeBytes": 804471463936, "diskFreeGiB": 749.222, "heavyEligible": true}
