telemetry-before: {"at": "2026-10-04T06:41:34.606998+00:00", "pageSize": 16384, "pages": {"Pages free": 23921, "Pages inactive": 311696, "Pages speculative": 2382}, "availableBytes": 5537775616, "availableGiB": 5.157, "pressure": 1, "cpuIdlePercent": 86.15, "cpu": "4.49% user, 9.34% sys, 86.15% idle", "diskFreeBytes": 804537708544, "diskFreeGiB": 749.284, "heavyEligible": true}
container=crew-v2-test-1fcbcd74-96ba-4335-a3ef-85b386093c76 id=691930fd024bc557c1b9571dd8ddef8e02eba066aabfccfce71d9ecfdfa154a8 port=27513
telemetry-node: {"at": "2026-10-04T06:41:36.383828+00:00", "pageSize": 16384, "pages": {"Pages free": 18751, "Pages inactive": 312029, "Pages speculative": 5932}, "availableBytes": 5516689408, "availableGiB": 5.138, "pressure": 1, "cpuIdlePercent": 83.89, "cpu": "5.36% user, 10.73% sys, 83.89% idle", "diskFreeBytes": 804488908800, "diskFreeGiB": 749.239, "heavyEligible": true}
exit=0
leftover_dbs=0
after-stop: 0 containers; node: 0
telemetry-after: {"at": "2026-10-04T06:41:48.403142+00:00", "pageSize": 16384, "pages": {"Pages free": 10728, "Pages inactive": 316435, "Pages speculative": 1814}, "availableBytes": 5389959168, "availableGiB": 5.02, "pressure": 1, "cpuIdlePercent": 84.1, "cpu": "5.10% user, 10.88% sys, 84.1% idle", "diskFreeBytes": 804471205888, "diskFreeGiB": 749.222, "heavyEligible": true}
