import pathlib,json,shutil,hashlib,subprocess,uuid,sys,os,re,time
repo=pathlib.Path('/Users/phannhatquang/.codex/worktrees/crew-v2-server/crew');root=pathlib.Path(__file__).parent;owner=json.loads((root/'owner.json').read_text());st=root.stat();assert(st.st_dev,st.st_ino,st.st_uid)==(owner['dev'],owner['ino'],owner['uid']);ev=repo/'plans/261002-0002-crew-v2/execution-phase05/task-5-evidence';runid=str(uuid.uuid4());kind=sys.argv[1];files=list((repo/'v2/server/src/attachments/extract').glob('*.ts'))+list((repo/'v2/server/test').glob('attachments-*.unit.test.ts'))+list((repo/'v2/server/test/fixtures/attachments').glob('*'));files += [repo/'v2/server/src/attachments/contracts.ts', repo/'v2/server/src/attachments/worker-protocol.ts', repo/'v2/server/src/attachments/worker-runner.ts', repo/'v2/server/src/attachments/worker-entry.ts'];manifest={}
for p in files:
 if not p.is_file() or p.is_symlink():raise RuntimeError('not regular')
 rel=p.relative_to(repo);dst=root/rel;dst.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(p,dst);manifest[str(rel)]={'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size}
# Frozen baseline and owned overlay are mounted separately from image-owned dependencies.
mounts=[(root/'v2/package.json','/fixture/v2/package.json'),(root/'v2/server/src','/fixture/v2/server/src'),(root/'v2/server/test','/fixture/v2/server/test'),(root/'v2/src','/fixture/v2/src'),(root/'v2/server/tsconfig.json','/fixture/v2/server/tsconfig.json')]
name='crew-v2-parser-test-'+runid;command=['node','--test','--test-concurrency=1','--test-reporter=tap','--test-name-pattern=attachment','test/attachments-formats.unit.test.ts','test/attachments-text-csv.unit.test.ts','test/attachments-pdf-image.unit.test.ts','test/attachments-ooxml.unit.test.ts'] if kind=='unit' else ['/opt/pnpm/bin/pnpm','exec','tsc','--noEmit','--project','test/tsconfig.json']
if kind=='fixture':command=['node','--input-type=module','-e',"import {makePng} from './test/fixtures/attachments/make-fixtures.ts';import {loadImage} from '@napi-rs/canvas';console.log('fixture');const b=makePng(3,2);console.log('png',b.length,Buffer.from(b).toString('hex'));const image=await loadImage(Buffer.from(b));console.log('decoded',image.width,image.height)"]
if kind=='pdf-api':command=['node','--input-type=module','-e',"import {readFileSync} from 'node:fs';import {getDocument} from 'pdfjs-dist/legacy/build/pdf.mjs';const task=getDocument({data:new Uint8Array(readFileSync('test/fixtures/attachments/launch.pdf'))});const doc=await task.promise;console.log('openAction',JSON.stringify(await doc.getOpenAction()));console.log('js',JSON.stringify(await doc.getJSActions()));console.log('fields',JSON.stringify(await doc.getFieldObjects()));console.log(JSON.stringify((await doc.getMetadata()).info));await task.destroy();"]
if kind=='pdf-compressed':command=['node','--input-type=module','-e',"import {readFileSync} from 'node:fs';import {PDFDocument,PDFName} from 'pdf-lib';const d=await PDFDocument.load(readFileSync('test/fixtures/attachments/text.pdf'),{updateMetadata:false});d.catalog.set(PDFName.of('OpenAction'),d.context.register(d.context.obj({S:PDFName.of('Launch'),F:'inert'})));const b=await d.save({useObjectStreams:true,addDefaultPage:false});console.log(JSON.stringify({fixture:'launch-compressed.pdf',base64:Buffer.from(b).toString('base64'),hasObjectStream:Buffer.from(b).includes(Buffer.from('/ObjStm'))}));"]
if kind=='native':command=['node','--input-type=module','-e',"import {createCanvas,loadImage} from '@napi-rs/canvas'; console.log('canvas');const b=createCanvas(3,2).toBuffer('image/png'); console.log('png',b.length);const image=await loadImage(b);console.log('decoded',image.width,image.height)"]
gate={'at':time.time(),'ruling':owner['resourceRuling'],'commands':[]}
def telemetry(argv):
 r=subprocess.run(argv,capture_output=True,text=True);gate['commands'].append({'argv':argv,'exit':r.returncode,'stdout':r.stdout,'stderr':r.stderr});assert r.returncode==0;return r.stdout
pressure=int(telemetry(['/usr/sbin/sysctl','-n','kern.memorystatus_vm_pressure_level']).strip())
vm=telemetry(['/usr/bin/vm_stat']);page=int(re.search(r'page size of (\d+)',vm).group(1));available=sum(int(re.search(r'Pages '+k+r':\s+(\d+)',vm).group(1)) for k in ['free','inactive','speculative'])*page
cpu=float(re.search(r'([\d.]+)% idle',telemetry(['/usr/bin/top','-l','1','-n','0'])).group(1));disk=os.statvfs(root).f_bavail*os.statvfs(root).f_frsize
own=telemetry(['/usr/local/bin/docker','ps','-q','--filter','label=crew.v2.fixture='+owner['nonce']]).strip()
gate.update({'pressure':pressure,'availableBytes':available,'cpuIdle':cpu,'diskAvailableBytes':disk,'ownLiveContainers':own})
assert pressure in [1,2] and available>=4*1024**3 and cpu>=50 and disk>=8*1024**3 and not own,gate
args=['/usr/local/bin/docker','create','--pull=never','--name',name,'--label','crew.v2.fixture='+owner['nonce'],'--label','crew.v2.challenge='+runid,'--network=none','--read-only','--cap-drop=ALL','--security-opt=no-new-privileges','--user=65532:65532','--memory=512m','--memory-swap=512m','--cpus=1','--pids-limit=32','--log-driver=none','--tmpfs','/tmp:rw,noexec,nosuid,size=16777216','--entrypoint',command[0]]
for src,dst in mounts:args+=['--mount',f'type=bind,src={src},dst={dst},readonly']
args+=[owner['image']]+command[1:];record={'runid':runid,'kind':kind,'argv':args,'parentPid':os.getpid(),'manifest':manifest,'nonce':owner['nonce'],'resourceGate':gate};receipt=ev/(runid+'.json');receipt.write_text(json.dumps(record,indent=2));created=subprocess.run(args,capture_output=True,text=True);record['createExit']=created.returncode
if created.returncode:record['createError']=created.stderr;receipt.write_text(json.dumps(record,indent=2));raise SystemExit(created.returncode)
cid=created.stdout.strip();assert len(cid)==64;record['containerId']=cid;receipt.write_text(json.dumps(record,indent=2));proc=subprocess.Popen(['/usr/local/bin/docker','start','--attach',cid],stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True);record['attachPid']=proc.pid;receipt.write_text(json.dumps(record,indent=2))
try:output,_=proc.communicate(timeout=120)
except subprocess.TimeoutExpired:
 subprocess.run(['/usr/local/bin/docker','stop','--time=1',cid],capture_output=True);output,_=proc.communicate(timeout=20)
record['attachExit']=proc.returncode;(ev/(runid+'.log')).write_text(output);print(output);check=subprocess.run(['/usr/local/bin/docker','inspect',cid],capture_output=True,text=True);rows=json.loads(check.stdout);row=rows[0];assert row['Id']==cid and row['Config']['Labels']['crew.v2.fixture']==owner['nonce'] and row['Image']==owner['image'];record['state']=row['State'];record['hostConfig']=row['HostConfig'];record['sourceStable']=all(hashlib.sha256((root/path).read_bytes()).hexdigest()==info['sha256'] for path,info in manifest.items());receipt.write_text(json.dumps(record,indent=2))
if row['State']['Running'] or row['State']['Pid']!=0 or row['State']['Status'] not in ['exited','dead']:raise RuntimeError('UNKNOWN retain')
removed=subprocess.run(['/usr/local/bin/docker','rm',cid],capture_output=True,text=True);record['removeExit']=removed.returncode;receipt.write_text(json.dumps(record,indent=2));print('RECEIPT',receipt,'EXIT',row['State']['ExitCode']);raise SystemExit(row['State']['ExitCode'])
